dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
//        maven {
//            url "https://maven.aliyun.com/repository/google"
//        }

//        maven {
//            url 'https://maven.aliyun.com/nexus/content/repositories/releases/'
//        }

        mavenCentral()
        maven {
            url 'https://maven.google.com/'
        }
        maven { url 'https://repo1.maven.org/maven2/' }
        google()
        maven {
            url "https://maven.aliyun.com/repository/public"
        }
        maven { url 'https://jitpack.io' }
    }
}


include ':app'
